from __future__ import annotations

from fastapi import HTTPException, status
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from src.modules.finance.model_finance import (
    FinanceTransaction,
    TransactionStatus,
)
from src.modules.hr.model_hr import PayrollRun
from src.security.dependencies import CurrentUser
from src.service.write_policy import CRUDWritePolicy


class PayrollRunWritePolicy(CRUDWritePolicy):
    """Protect payroll/finance integrity during payroll deletion.

    Finance transactions generated by payroll cannot be deleted through the
    generic Finance endpoint. A draft generated transaction may only be
    removed together with its source payroll run. Posted, void, or cancelled
    transactions keep the payroll run immutable for audit purposes.
    """

    async def before_delete(
        self,
        *,
        db: AsyncSession,
        existing: PayrollRun,
        current_user: CurrentUser,
    ) -> None:
        del current_user

        link_conditions = [
            (
                (FinanceTransaction.source_module == "hr_payroll")
                & (FinanceTransaction.source_id == existing.id)
            )
        ]

        if existing.finance_transaction_id is not None:
            link_conditions.append(
                FinanceTransaction.id == existing.finance_transaction_id
            )

        result = await db.execute(
            select(FinanceTransaction)
            .where(
                FinanceTransaction.company_id == existing.company_id,
                or_(*link_conditions),
            )
            .with_for_update()
        )
        transaction = result.scalars().first()

        if transaction is None:
            return

        is_payroll_transaction = (
            transaction.source_module == "hr_payroll"
            and transaction.source_id == existing.id
            and transaction.company_id == existing.company_id
        )
        if not is_payroll_transaction:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=(
                    "Payroll finance transaction link is inconsistent and "
                    "must be reviewed before deletion"
                ),
            )

        if transaction.status != TransactionStatus.DRAFT:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=(
                    "Payroll runs with posted, void, or cancelled finance "
                    "transactions cannot be deleted"
                ),
            )

        # Clear the source link before deleting the generated draft. Both
        # changes are flushed in the same database transaction as the payroll
        # deletion performed by the generic CRUD service.
        existing.finance_transaction_id = None
        await db.delete(transaction)
        await db.flush()
