"""initial complete schema

Revision ID: 959810c0f3b0
Revises: 
Create Date: 2026-07-08 16:23:06.057393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959810c0f3b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='company_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_number')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=80), nullable=False),
    sa.Column('feature_code', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'MANAGE', name='user_permission_action_enum'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'feature_code', 'action', name='uq_user_permission_module_feature_action')
    )
    op.create_index('ix_user_permissions_module_feature', 'user_permissions', ['module_code', 'feature_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'INVITED', 'SUSPENDED', name='user_status_enum'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('company_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('branch_type', sa.Enum('HEAD_OFFICE', 'BRANCH', 'OUTLET', 'WAREHOUSE', name='branch_type_enum'), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('is_head_office', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_company_branch_company_code')
    )
    op.create_index('ix_company_branches_company_active', 'company_branches', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_company_branches_company_id'), 'company_branches', ['company_id'], unique=False)
    op.create_table('finance_accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LOCKED', name='period_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period_number', name='uq_finance_period_company_year_period')
    )
    op.create_index(op.f('ix_finance_accounting_periods_company_id'), 'finance_accounting_periods', ['company_id'], unique=False)
    op.create_table('finance_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', 'COST_OF_GOODS_SOLD', 'TAX', name='finance_account_type_enum'), nullable=False),
    sa.Column('normal_balance', sa.Enum('DEBIT', 'CREDIT', name='finance_normal_balance_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_cash_account', sa.Boolean(), nullable=False),
    sa.Column('is_bank_account', sa.Boolean(), nullable=False),
    sa.Column('is_tax_account', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_finance_account_company_code')
    )
    op.create_index(op.f('ix_finance_accounts_company_id'), 'finance_accounts', ['company_id'], unique=False)
    op.create_index('ix_finance_accounts_company_type', 'finance_accounts', ['company_id', 'account_type'], unique=False)
    op.create_index(op.f('ix_finance_accounts_parent_account_id'), 'finance_accounts', ['parent_account_id'], unique=False)
    op.create_table('finance_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='finance_budget_status_enum'), nullable=False),
    sa.Column('total_budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'name', name='uq_finance_budget_company_year_name')
    )
    op.create_index(op.f('ix_finance_budgets_company_id'), 'finance_budgets', ['company_id'], unique=False)
    op.create_table('finance_tax_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('tax_type', sa.Enum('PPN', 'PPH_21', 'PPH_22', 'PPH_23', 'PPH_25', 'PPH_FINAL', 'OTHER', name='finance_tax_type_enum'), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_tax_rates_company_id'), 'finance_tax_rates', ['company_id'], unique=False)
    op.create_index('ix_finance_tax_rates_company_type', 'finance_tax_rates', ['company_id', 'tax_type'], unique=False)
    op.create_table('hr_leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('default_days_per_year', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_leave_type_company_code')
    )
    op.create_index(op.f('ix_hr_leave_types_company_id'), 'hr_leave_types', ['company_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_product_category_company_code')
    )
    op.create_index('ix_product_categories_company_active', 'product_categories', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_categories_parent_category_id'), 'product_categories', ['parent_category_id'], unique=False)
    op.create_table('product_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REVIEW', name='product_supplier_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_suppliers_company_id'), 'product_suppliers', ['company_id'], unique=False)
    op.create_index('ix_product_suppliers_company_status', 'product_suppliers', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_suppliers_name'), 'product_suppliers', ['name'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='system_setting_status_enum'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_system_settings_company_key')
    )
    op.create_index('ix_system_settings_company_category', 'system_settings', ['company_id', 'category'], unique=False)
    op.create_index(op.f('ix_system_settings_company_id'), 'system_settings', ['company_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_owner_role', sa.Boolean(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_user_role_company_code')
    )
    op.create_index('ix_user_roles_company_active', 'user_roles', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_roles_company_id'), 'user_roles', ['company_id'], unique=False)
    op.create_table('crm_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('leads_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='crm_campaign_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_campaigns_branch_id'), 'crm_campaigns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_crm_campaigns_company_id'), 'crm_campaigns', ['company_id'], unique=False)
    op.create_index('ix_crm_campaigns_company_status', 'crm_campaigns', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_crm_campaigns_name'), 'crm_campaigns', ['name'], unique=False)
    op.create_table('crm_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'UNQUALIFIED', 'CONVERTED', name='lead_status_enum'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_branch_id'), 'crm_leads', ['branch_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_company_id'), 'crm_leads', ['company_id'], unique=False)
    op.create_index('ix_crm_leads_company_status', 'crm_leads', ['company_id', 'status'], unique=False)
    op.create_index('ix_crm_leads_followup', 'crm_leads', ['company_id', 'next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_crm_leads_name'), 'crm_leads', ['name'], unique=False)
    op.create_index('ix_crm_leads_owner_status', 'crm_leads', ['owner_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_crm_leads_owner_user_id'), 'crm_leads', ['owner_user_id'], unique=False)
    op.create_table('finance_balance_sheet_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retained_earnings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_balance_sheet_snapshots_company_date', 'finance_balance_sheet_snapshots', ['company_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_finance_balance_sheet_snapshots_company_id'), 'finance_balance_sheet_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_balance_sheet_snapshots_period_id'), 'finance_balance_sheet_snapshots', ['period_id'], unique=False)
    op.create_table('finance_budget_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('variance_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_budget_lines_account_id'), 'finance_budget_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_budget_lines_budget_id'), 'finance_budget_lines', ['budget_id'], unique=False)
    op.create_table('finance_cash_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('account_holder_name', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_finance_cash_account_company_name')
    )
    op.create_index(op.f('ix_finance_cash_accounts_account_id'), 'finance_cash_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_cash_accounts_company_id'), 'finance_cash_accounts', ['company_id'], unique=False)
    op.create_table('finance_cashflow_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('beginning_cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('operating_cash_in', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('operating_cash_out', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('investing_cash_in', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('investing_cash_out', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('financing_cash_in', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('financing_cash_out', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ending_cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_cashflow_snapshots_company_date', 'finance_cashflow_snapshots', ['company_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_finance_cashflow_snapshots_company_id'), 'finance_cashflow_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_cashflow_snapshots_period_id'), 'finance_cashflow_snapshots', ['period_id'], unique=False)
    op.create_table('finance_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='finance_invoice_status_enum'), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'invoice_no', name='uq_finance_invoice_company_no')
    )
    op.create_index(op.f('ix_finance_invoices_branch_id'), 'finance_invoices', ['branch_id'], unique=False)
    op.create_index('ix_finance_invoices_company_due', 'finance_invoices', ['company_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_finance_invoices_company_id'), 'finance_invoices', ['company_id'], unique=False)
    op.create_index('ix_finance_invoices_company_status', 'finance_invoices', ['company_id', 'status'], unique=False)
    op.create_table('finance_margin_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('object_name', sa.String(length=150), nullable=True),
    sa.Column('revenue_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cogs_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_margin_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_margin_snapshots_company_id'), 'finance_margin_snapshots', ['company_id'], unique=False)
    op.create_index('ix_finance_margin_snapshots_company_object', 'finance_margin_snapshots', ['company_id', 'object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_finance_margin_snapshots_object_id'), 'finance_margin_snapshots', ['object_id'], unique=False)
    op.create_index(op.f('ix_finance_margin_snapshots_period_id'), 'finance_margin_snapshots', ['period_id'], unique=False)
    op.create_table('finance_profit_loss_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_cogs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('operating_expense', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('operating_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_expense', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_expense', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_margin_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('net_margin_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_pl_snapshots_company_date', 'finance_profit_loss_snapshots', ['company_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_finance_profit_loss_snapshots_company_id'), 'finance_profit_loss_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_profit_loss_snapshots_period_id'), 'finance_profit_loss_snapshots', ['period_id'], unique=False)
    op.create_table('hr_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_no', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RESIGNED', 'SUSPENDED', name='employee_status_enum'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('resign_date', sa.Date(), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_no', name='uq_hr_employee_company_no')
    )
    op.create_index(op.f('ix_hr_employees_branch_id'), 'hr_employees', ['branch_id'], unique=False)
    op.create_index('ix_hr_employees_company_branch_status', 'hr_employees', ['company_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_hr_employees_company_id'), 'hr_employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_employees_full_name'), 'hr_employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_hr_employees_user_id'), 'hr_employees', ['user_id'], unique=False)
    op.create_table('hr_kpi_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_kpi_indicator_company_code')
    )
    op.create_index(op.f('ix_hr_kpi_indicators_branch_id'), 'hr_kpi_indicators', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_kpi_indicators_company_id'), 'hr_kpi_indicators', ['company_id'], unique=False)
    op.create_index('ix_kpi_indicators_company_active', 'hr_kpi_indicators', ['company_id', 'is_active'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.Enum('PHYSICAL', 'DIGITAL', 'SERVICE', name='product_type_enum'), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='product_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_products_company_sku')
    )
    op.create_index(op.f('ix_products_branch_id'), 'products', ['branch_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_company_category', 'products', ['company_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index('ix_products_company_status', 'products', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_created_by_id'), 'products', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('user_company_accesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('default_branch_id', sa.UUID(), nullable=True),
    sa.Column('access_scope', sa.Enum('COMPANY', 'ALL_BRANCHES', 'SELECTED_BRANCHES', name='user_access_scope_enum'), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_access_user_company')
    )
    op.create_index('ix_user_company_access_company_active', 'user_company_accesses', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_user_company_access_user_active', 'user_company_accesses', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_company_accesses_company_id'), 'user_company_accesses', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_company_accesses_default_branch_id'), 'user_company_accesses', ['default_branch_id'], unique=False)
    op.create_index(op.f('ix_user_company_accesses_role_id'), 'user_company_accesses', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_company_accesses_user_id'), 'user_company_accesses', ['user_id'], unique=False)
    op.create_table('user_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['user_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_user_role_permission')
    )
    op.create_index(op.f('ix_user_role_permissions_permission_id'), 'user_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_role_permissions_role_id'), 'user_role_permissions', ['role_id'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_branch_id'), 'crm_contacts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index('ix_crm_contacts_company_owner', 'crm_contacts', ['company_id', 'owner_user_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_lead_id'), 'crm_contacts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_name'), 'crm_contacts', ['name'], unique=False)
    op.create_index(op.f('ix_crm_contacts_owner_user_id'), 'crm_contacts', ['owner_user_id'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('cash_account_id', sa.UUID(), nullable=True),
    sa.Column('transaction_no', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'TAX_PAYMENT', 'REFUND', 'ADJUSTMENT', name='finance_transaction_type_enum'), nullable=False),
    sa.Column('cashflow_activity', sa.Enum('OPERATING', 'INVESTING', 'FINANCING', name='finance_cashflow_activity_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', 'CANCELLED', name='finance_transaction_status_enum'), nullable=False),
    sa.Column('counterparty_name', sa.String(length=150), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('source_module', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cash_account_id'], ['finance_cash_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'transaction_no', name='uq_finance_transaction_company_no')
    )
    op.create_index(op.f('ix_finance_transactions_branch_id'), 'finance_transactions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_cash_account_id'), 'finance_transactions', ['cash_account_id'], unique=False)
    op.create_index('ix_finance_transactions_company_date_type', 'finance_transactions', ['company_id', 'transaction_date', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_finance_transactions_company_id'), 'finance_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_period_id'), 'finance_transactions', ['period_id'], unique=False)
    op.create_table('hr_attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'SICK', 'HOLIDAY', name='attendance_status_enum'), nullable=False),
    sa.Column('work_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index('ix_attendance_company_date', 'hr_attendance_records', ['company_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_hr_attendance_records_branch_id'), 'hr_attendance_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_attendance_records_company_id'), 'hr_attendance_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_attendance_records_employee_id'), 'hr_attendance_records', ['employee_id'], unique=False)
    op.create_table('hr_kpi_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='kpi_review_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_kpi_reviews_branch_id'), 'hr_kpi_reviews', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_kpi_reviews_company_id'), 'hr_kpi_reviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_kpi_reviews_employee_id'), 'hr_kpi_reviews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_kpi_reviews_reviewer_user_id'), 'hr_kpi_reviews', ['reviewer_user_id'], unique=False)
    op.create_index('ix_kpi_reviews_company_period', 'hr_kpi_reviews', ['company_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_kpi_reviews_employee_period', 'hr_kpi_reviews', ['employee_id', 'period_start', 'period_end'], unique=False)
    op.create_table('hr_leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitled_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['hr_leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balance_employee_type_year')
    )
    op.create_index(op.f('ix_hr_leave_balances_employee_id'), 'hr_leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_balances_leave_type_id'), 'hr_leave_balances', ['leave_type_id'], unique=False)
    op.create_table('hr_leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='approval_status_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['hr_leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_leave_requests_approved_by_id'), 'hr_leave_requests', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_requests_branch_id'), 'hr_leave_requests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_requests_company_id'), 'hr_leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_requests_employee_id'), 'hr_leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_requests_leave_type_id'), 'hr_leave_requests', ['leave_type_id'], unique=False)
    op.create_index('ix_leave_requests_company_status', 'hr_leave_requests', ['company_id', 'status'], unique=False)
    op.create_index('ix_leave_requests_employee_date', 'hr_leave_requests', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_table('hr_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='hr_task_status_enum'), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('weight_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('completion_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_tasks_assigned_by_id'), 'hr_tasks', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_hr_tasks_branch_id'), 'hr_tasks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_tasks_company_id'), 'hr_tasks', ['company_id'], unique=False)
    op.create_index('ix_hr_tasks_company_status_due', 'hr_tasks', ['company_id', 'status', 'due_date'], unique=False)
    op.create_index(op.f('ix_hr_tasks_employee_id'), 'hr_tasks', ['employee_id'], unique=False)
    op.create_index('ix_hr_tasks_employee_status', 'hr_tasks', ['employee_id', 'status'], unique=False)
    op.create_table('product_stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER', 'SALES', 'PURCHASE', name='stock_movement_type_enum'), nullable=False),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_stock_movements_branch_id'), 'product_stock_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_product_stock_movements_company_id'), 'product_stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_stock_movements_created_by_id'), 'product_stock_movements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_product_stock_movements_product_id'), 'product_stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_company_date', 'product_stock_movements', ['company_id', 'movement_date'], unique=False)
    op.create_index('ix_stock_movements_product_date', 'product_stock_movements', ['product_id', 'movement_date'], unique=False)
    op.create_index('ix_stock_movements_source', 'product_stock_movements', ['source_module', 'source_id'], unique=False)
    op.create_table('product_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_product_stock_product_branch')
    )
    op.create_index(op.f('ix_product_stocks_branch_id'), 'product_stocks', ['branch_id'], unique=False)
    op.create_index('ix_product_stocks_branch_product', 'product_stocks', ['branch_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_product_stocks_company_id'), 'product_stocks', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_stocks_product_id'), 'product_stocks', ['product_id'], unique=False)
    op.create_table('user_branch_accesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_access_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('can_manage_branch', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_access_id'], ['user_company_accesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_access_id', 'branch_id', name='uq_user_branch_access')
    )
    op.create_index(op.f('ix_user_branch_accesses_branch_id'), 'user_branch_accesses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_branch_accesses_company_access_id'), 'user_branch_accesses', ['company_access_id'], unique=False)
    op.create_table('crm_deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.Enum('PROSPECTING', 'QUALIFICATION', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', name='deal_stage_enum'), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('probability_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('won_lost_reason', sa.Text(), nullable=True),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deals_branch_id'), 'crm_deals', ['branch_id'], unique=False)
    op.create_index('ix_crm_deals_close_date', 'crm_deals', ['company_id', 'expected_close_date'], unique=False)
    op.create_index(op.f('ix_crm_deals_company_id'), 'crm_deals', ['company_id'], unique=False)
    op.create_index('ix_crm_deals_company_stage', 'crm_deals', ['company_id', 'stage'], unique=False)
    op.create_index(op.f('ix_crm_deals_contact_id'), 'crm_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_finance_transaction_id'), 'crm_deals', ['finance_transaction_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_lead_id'), 'crm_deals', ['lead_id'], unique=False)
    op.create_index('ix_crm_deals_owner_stage', 'crm_deals', ['owner_user_id', 'stage'], unique=False)
    op.create_index(op.f('ix_crm_deals_owner_user_id'), 'crm_deals', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_title'), 'crm_deals', ['title'], unique=False)
    op.create_table('finance_journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('journal_no', sa.String(length=100), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='finance_journal_status_enum'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'journal_no', name='uq_finance_journal_company_no')
    )
    op.create_index('ix_finance_journal_company_date', 'finance_journal_entries', ['company_id', 'journal_date'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_company_id'), 'finance_journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_period_id'), 'finance_journal_entries', ['period_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_transaction_id'), 'finance_journal_entries', ['transaction_id'], unique=False)
    op.create_table('finance_tax_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('tax_rate_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('tax_type', sa.Enum('PPN', 'PPH_21', 'PPH_22', 'PPH_23', 'PPH_25', 'PPH_FINAL', 'OTHER', name='finance_tax_record_type_enum'), nullable=False),
    sa.Column('tax_period', sa.String(length=20), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACCRUED', 'PAID', 'REPORTED', 'CANCELLED', name='finance_tax_record_status_enum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['finance_accounting_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['finance_tax_rates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_tax_records_company_id'), 'finance_tax_records', ['company_id'], unique=False)
    op.create_index('ix_finance_tax_records_company_period_type', 'finance_tax_records', ['company_id', 'tax_period', 'tax_type'], unique=False)
    op.create_index(op.f('ix_finance_tax_records_period_id'), 'finance_tax_records', ['period_id'], unique=False)
    op.create_index(op.f('ix_finance_tax_records_tax_rate_id'), 'finance_tax_records', ['tax_rate_id'], unique=False)
    op.create_index(op.f('ix_finance_tax_records_transaction_id'), 'finance_tax_records', ['transaction_id'], unique=False)
    op.create_table('finance_transaction_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['finance_tax_rates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_transaction_lines_account_id'), 'finance_transaction_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_lines_tax_rate_id'), 'finance_transaction_lines', ['tax_rate_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_lines_transaction_id'), 'finance_transaction_lines', ['transaction_id'], unique=False)
    op.create_table('hr_kpi_review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['hr_kpi_indicators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['hr_kpi_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_kpi_review_items_indicator_id'), 'hr_kpi_review_items', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_hr_kpi_review_items_review_id'), 'hr_kpi_review_items', ['review_id'], unique=False)
    op.create_table('hr_payroll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('payroll_no', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'APPROVED', 'PAID', 'CANCELLED', name='payroll_status_enum'), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'payroll_no', name='uq_payroll_company_no')
    )
    op.create_index(op.f('ix_hr_payroll_runs_branch_id'), 'hr_payroll_runs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_company_id'), 'hr_payroll_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_created_by_id'), 'hr_payroll_runs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_finance_transaction_id'), 'hr_payroll_runs', ['finance_transaction_id'], unique=False)
    op.create_index('ix_payroll_runs_company_period', 'hr_payroll_runs', ['company_id', 'period_start', 'period_end'], unique=False)
    op.create_table('crm_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'WHATSAPP', 'NOTE', 'TASK', name='crm_activity_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'DONE', 'CANCELLED', 'OVERDUE', name='crm_activity_status_enum'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crm_activities_assigned_due', 'crm_activities', ['assigned_user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_crm_activities_assigned_user_id'), 'crm_activities', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_branch_id'), 'crm_activities', ['branch_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_company_id'), 'crm_activities', ['company_id'], unique=False)
    op.create_index('ix_crm_activities_company_status_due', 'crm_activities', ['company_id', 'status', 'due_at'], unique=False)
    op.create_index(op.f('ix_crm_activities_contact_id'), 'crm_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_deal_id'), 'crm_activities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_lead_id'), 'crm_activities', ['lead_id'], unique=False)
    op.create_table('crm_deal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deal_items_deal_id'), 'crm_deal_items', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_deal_items_product_id'), 'crm_deal_items', ['product_id'], unique=False)
    op.create_table('finance_journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['finance_journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_lines_account_id'), 'finance_journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_lines_journal_entry_id'), 'finance_journal_lines', ['journal_entry_id'], unique=False)
    op.create_table('hr_payroll_slips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allowance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['hr_payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_slip_run_employee')
    )
    op.create_index(op.f('ix_hr_payroll_slips_employee_id'), 'hr_payroll_slips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_slips_payroll_run_id'), 'hr_payroll_slips', ['payroll_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_payroll_slips_payroll_run_id'), table_name='hr_payroll_slips')
    op.drop_index(op.f('ix_hr_payroll_slips_employee_id'), table_name='hr_payroll_slips')
    op.drop_table('hr_payroll_slips')
    op.drop_index(op.f('ix_finance_journal_lines_journal_entry_id'), table_name='finance_journal_lines')
    op.drop_index(op.f('ix_finance_journal_lines_account_id'), table_name='finance_journal_lines')
    op.drop_table('finance_journal_lines')
    op.drop_index(op.f('ix_crm_deal_items_product_id'), table_name='crm_deal_items')
    op.drop_index(op.f('ix_crm_deal_items_deal_id'), table_name='crm_deal_items')
    op.drop_table('crm_deal_items')
    op.drop_index(op.f('ix_crm_activities_lead_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_deal_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_contact_id'), table_name='crm_activities')
    op.drop_index('ix_crm_activities_company_status_due', table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_company_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_branch_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_assigned_user_id'), table_name='crm_activities')
    op.drop_index('ix_crm_activities_assigned_due', table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index('ix_payroll_runs_company_period', table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_finance_transaction_id'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_created_by_id'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_company_id'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_branch_id'), table_name='hr_payroll_runs')
    op.drop_table('hr_payroll_runs')
    op.drop_index(op.f('ix_hr_kpi_review_items_review_id'), table_name='hr_kpi_review_items')
    op.drop_index(op.f('ix_hr_kpi_review_items_indicator_id'), table_name='hr_kpi_review_items')
    op.drop_table('hr_kpi_review_items')
    op.drop_index(op.f('ix_finance_transaction_lines_transaction_id'), table_name='finance_transaction_lines')
    op.drop_index(op.f('ix_finance_transaction_lines_tax_rate_id'), table_name='finance_transaction_lines')
    op.drop_index(op.f('ix_finance_transaction_lines_account_id'), table_name='finance_transaction_lines')
    op.drop_table('finance_transaction_lines')
    op.drop_index(op.f('ix_finance_tax_records_transaction_id'), table_name='finance_tax_records')
    op.drop_index(op.f('ix_finance_tax_records_tax_rate_id'), table_name='finance_tax_records')
    op.drop_index(op.f('ix_finance_tax_records_period_id'), table_name='finance_tax_records')
    op.drop_index('ix_finance_tax_records_company_period_type', table_name='finance_tax_records')
    op.drop_index(op.f('ix_finance_tax_records_company_id'), table_name='finance_tax_records')
    op.drop_table('finance_tax_records')
    op.drop_index(op.f('ix_finance_journal_entries_transaction_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_period_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_company_id'), table_name='finance_journal_entries')
    op.drop_index('ix_finance_journal_company_date', table_name='finance_journal_entries')
    op.drop_table('finance_journal_entries')
    op.drop_index(op.f('ix_crm_deals_title'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_owner_user_id'), table_name='crm_deals')
    op.drop_index('ix_crm_deals_owner_stage', table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_lead_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_finance_transaction_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_contact_id'), table_name='crm_deals')
    op.drop_index('ix_crm_deals_company_stage', table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_company_id'), table_name='crm_deals')
    op.drop_index('ix_crm_deals_close_date', table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_branch_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_user_branch_accesses_company_access_id'), table_name='user_branch_accesses')
    op.drop_index(op.f('ix_user_branch_accesses_branch_id'), table_name='user_branch_accesses')
    op.drop_table('user_branch_accesses')
    op.drop_index(op.f('ix_product_stocks_product_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_company_id'), table_name='product_stocks')
    op.drop_index('ix_product_stocks_branch_product', table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_branch_id'), table_name='product_stocks')
    op.drop_table('product_stocks')
    op.drop_index('ix_stock_movements_source', table_name='product_stock_movements')
    op.drop_index('ix_stock_movements_product_date', table_name='product_stock_movements')
    op.drop_index('ix_stock_movements_company_date', table_name='product_stock_movements')
    op.drop_index(op.f('ix_product_stock_movements_product_id'), table_name='product_stock_movements')
    op.drop_index(op.f('ix_product_stock_movements_created_by_id'), table_name='product_stock_movements')
    op.drop_index(op.f('ix_product_stock_movements_company_id'), table_name='product_stock_movements')
    op.drop_index(op.f('ix_product_stock_movements_branch_id'), table_name='product_stock_movements')
    op.drop_table('product_stock_movements')
    op.drop_index('ix_hr_tasks_employee_status', table_name='hr_tasks')
    op.drop_index(op.f('ix_hr_tasks_employee_id'), table_name='hr_tasks')
    op.drop_index('ix_hr_tasks_company_status_due', table_name='hr_tasks')
    op.drop_index(op.f('ix_hr_tasks_company_id'), table_name='hr_tasks')
    op.drop_index(op.f('ix_hr_tasks_branch_id'), table_name='hr_tasks')
    op.drop_index(op.f('ix_hr_tasks_assigned_by_id'), table_name='hr_tasks')
    op.drop_table('hr_tasks')
    op.drop_index('ix_leave_requests_employee_date', table_name='hr_leave_requests')
    op.drop_index('ix_leave_requests_company_status', table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_leave_type_id'), table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_employee_id'), table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_company_id'), table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_branch_id'), table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_approved_by_id'), table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_balances_leave_type_id'), table_name='hr_leave_balances')
    op.drop_index(op.f('ix_hr_leave_balances_employee_id'), table_name='hr_leave_balances')
    op.drop_table('hr_leave_balances')
    op.drop_index('ix_kpi_reviews_employee_period', table_name='hr_kpi_reviews')
    op.drop_index('ix_kpi_reviews_company_period', table_name='hr_kpi_reviews')
    op.drop_index(op.f('ix_hr_kpi_reviews_reviewer_user_id'), table_name='hr_kpi_reviews')
    op.drop_index(op.f('ix_hr_kpi_reviews_employee_id'), table_name='hr_kpi_reviews')
    op.drop_index(op.f('ix_hr_kpi_reviews_company_id'), table_name='hr_kpi_reviews')
    op.drop_index(op.f('ix_hr_kpi_reviews_branch_id'), table_name='hr_kpi_reviews')
    op.drop_table('hr_kpi_reviews')
    op.drop_index(op.f('ix_hr_attendance_records_employee_id'), table_name='hr_attendance_records')
    op.drop_index(op.f('ix_hr_attendance_records_company_id'), table_name='hr_attendance_records')
    op.drop_index(op.f('ix_hr_attendance_records_branch_id'), table_name='hr_attendance_records')
    op.drop_index('ix_attendance_company_date', table_name='hr_attendance_records')
    op.drop_table('hr_attendance_records')
    op.drop_index(op.f('ix_finance_transactions_period_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_company_id'), table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_company_date_type', table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_cash_account_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_branch_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index(op.f('ix_crm_contacts_owner_user_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_name'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_lead_id'), table_name='crm_contacts')
    op.drop_index('ix_crm_contacts_company_owner', table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_branch_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_user_role_permissions_role_id'), table_name='user_role_permissions')
    op.drop_index(op.f('ix_user_role_permissions_permission_id'), table_name='user_role_permissions')
    op.drop_table('user_role_permissions')
    op.drop_index(op.f('ix_user_company_accesses_user_id'), table_name='user_company_accesses')
    op.drop_index(op.f('ix_user_company_accesses_role_id'), table_name='user_company_accesses')
    op.drop_index(op.f('ix_user_company_accesses_default_branch_id'), table_name='user_company_accesses')
    op.drop_index(op.f('ix_user_company_accesses_company_id'), table_name='user_company_accesses')
    op.drop_index('ix_user_company_access_user_active', table_name='user_company_accesses')
    op.drop_index('ix_user_company_access_company_active', table_name='user_company_accesses')
    op.drop_table('user_company_accesses')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_created_by_id'), table_name='products')
    op.drop_index('ix_products_company_status', table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index('ix_products_company_category', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_branch_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_kpi_indicators_company_active', table_name='hr_kpi_indicators')
    op.drop_index(op.f('ix_hr_kpi_indicators_company_id'), table_name='hr_kpi_indicators')
    op.drop_index(op.f('ix_hr_kpi_indicators_branch_id'), table_name='hr_kpi_indicators')
    op.drop_table('hr_kpi_indicators')
    op.drop_index(op.f('ix_hr_employees_user_id'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_full_name'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_company_id'), table_name='hr_employees')
    op.drop_index('ix_hr_employees_company_branch_status', table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_branch_id'), table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_index(op.f('ix_finance_profit_loss_snapshots_period_id'), table_name='finance_profit_loss_snapshots')
    op.drop_index(op.f('ix_finance_profit_loss_snapshots_company_id'), table_name='finance_profit_loss_snapshots')
    op.drop_index('ix_finance_pl_snapshots_company_date', table_name='finance_profit_loss_snapshots')
    op.drop_table('finance_profit_loss_snapshots')
    op.drop_index(op.f('ix_finance_margin_snapshots_period_id'), table_name='finance_margin_snapshots')
    op.drop_index(op.f('ix_finance_margin_snapshots_object_id'), table_name='finance_margin_snapshots')
    op.drop_index('ix_finance_margin_snapshots_company_object', table_name='finance_margin_snapshots')
    op.drop_index(op.f('ix_finance_margin_snapshots_company_id'), table_name='finance_margin_snapshots')
    op.drop_table('finance_margin_snapshots')
    op.drop_index('ix_finance_invoices_company_status', table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_company_id'), table_name='finance_invoices')
    op.drop_index('ix_finance_invoices_company_due', table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_branch_id'), table_name='finance_invoices')
    op.drop_table('finance_invoices')
    op.drop_index(op.f('ix_finance_cashflow_snapshots_period_id'), table_name='finance_cashflow_snapshots')
    op.drop_index(op.f('ix_finance_cashflow_snapshots_company_id'), table_name='finance_cashflow_snapshots')
    op.drop_index('ix_finance_cashflow_snapshots_company_date', table_name='finance_cashflow_snapshots')
    op.drop_table('finance_cashflow_snapshots')
    op.drop_index(op.f('ix_finance_cash_accounts_company_id'), table_name='finance_cash_accounts')
    op.drop_index(op.f('ix_finance_cash_accounts_account_id'), table_name='finance_cash_accounts')
    op.drop_table('finance_cash_accounts')
    op.drop_index(op.f('ix_finance_budget_lines_budget_id'), table_name='finance_budget_lines')
    op.drop_index(op.f('ix_finance_budget_lines_account_id'), table_name='finance_budget_lines')
    op.drop_table('finance_budget_lines')
    op.drop_index(op.f('ix_finance_balance_sheet_snapshots_period_id'), table_name='finance_balance_sheet_snapshots')
    op.drop_index(op.f('ix_finance_balance_sheet_snapshots_company_id'), table_name='finance_balance_sheet_snapshots')
    op.drop_index('ix_finance_balance_sheet_snapshots_company_date', table_name='finance_balance_sheet_snapshots')
    op.drop_table('finance_balance_sheet_snapshots')
    op.drop_index(op.f('ix_crm_leads_owner_user_id'), table_name='crm_leads')
    op.drop_index('ix_crm_leads_owner_status', table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_name'), table_name='crm_leads')
    op.drop_index('ix_crm_leads_followup', table_name='crm_leads')
    op.drop_index('ix_crm_leads_company_status', table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_company_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_branch_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_campaigns_name'), table_name='crm_campaigns')
    op.drop_index('ix_crm_campaigns_company_status', table_name='crm_campaigns')
    op.drop_index(op.f('ix_crm_campaigns_company_id'), table_name='crm_campaigns')
    op.drop_index(op.f('ix_crm_campaigns_branch_id'), table_name='crm_campaigns')
    op.drop_table('crm_campaigns')
    op.drop_index(op.f('ix_user_roles_company_id'), table_name='user_roles')
    op.drop_index('ix_user_roles_company_active', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_system_settings_company_id'), table_name='system_settings')
    op.drop_index('ix_system_settings_company_category', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_product_suppliers_name'), table_name='product_suppliers')
    op.drop_index('ix_product_suppliers_company_status', table_name='product_suppliers')
    op.drop_index(op.f('ix_product_suppliers_company_id'), table_name='product_suppliers')
    op.drop_table('product_suppliers')
    op.drop_index(op.f('ix_product_categories_parent_category_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_index('ix_product_categories_company_active', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_hr_leave_types_company_id'), table_name='hr_leave_types')
    op.drop_table('hr_leave_types')
    op.drop_index('ix_finance_tax_rates_company_type', table_name='finance_tax_rates')
    op.drop_index(op.f('ix_finance_tax_rates_company_id'), table_name='finance_tax_rates')
    op.drop_table('finance_tax_rates')
    op.drop_index(op.f('ix_finance_budgets_company_id'), table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index(op.f('ix_finance_accounts_parent_account_id'), table_name='finance_accounts')
    op.drop_index('ix_finance_accounts_company_type', table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_company_id'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_index(op.f('ix_finance_accounting_periods_company_id'), table_name='finance_accounting_periods')
    op.drop_table('finance_accounting_periods')
    op.drop_index(op.f('ix_company_branches_company_id'), table_name='company_branches')
    op.drop_index('ix_company_branches_company_active', table_name='company_branches')
    op.drop_table('company_branches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_permissions_module_feature', table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
