import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import type { ModuleColumn, ModuleRow } from "@/types/modules";

function safeFileName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
}

function toRupiah(value: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
}

function extractNumber(value?: string) {
  if (!value) return 0;

  const normalized = value.replace(/[^\d]/g, "");
  return Number(normalized || 0);
}

export function exportRowsToExcel({
  filename,
  sheetName = "Data",
  columns,
  rows,
}: {
  filename: string;
  sheetName?: string;
  columns: ModuleColumn[];
  rows: ModuleRow[];
}) {
  const data = rows.map((row) => {
    const item: Record<string, string> = {};

    columns.forEach((column) => {
      item[column.label] = row[column.key] ?? "";
    });

    return item;
  });

  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, `${safeFileName(filename)}.xlsx`);
}

export function exportRowsToPDF({
  filename,
  title,
  description,
  columns,
  rows,
}: {
  filename: string;
  title: string;
  description?: string;
  columns: ModuleColumn[];
  rows: ModuleRow[];
}) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "pt",
    format: "a4",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 40, 44);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(description ?? "Generated by DashAI ERP", 40, 64);

  doc.setFontSize(9);
  doc.text(`Generated at: ${new Date().toLocaleString("id-ID")}`, 40, 82);

  autoTable(doc, {
    startY: 105,
    head: [columns.map((column) => column.label)],
    body: rows.map((row) => columns.map((column) => row[column.key] ?? "-")),
    styles: {
      fontSize: 8,
      cellPadding: 7,
    },
    headStyles: {
      fillColor: [15, 42, 95],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  doc.save(`${safeFileName(filename)}.pdf`);
}

export function exportInvoiceToPDF(row: ModuleRow) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const invoiceNumber = row.invoice || row.code || `INV-${Date.now()}`;
  const client = row.client || row.customer || row.company || "Customer";
  const baseAmount = extractNumber(row.amount || row.value || row.total);
  const tax = Math.round(baseAmount * 0.11);
  const grandTotal = baseAmount + tax;

  doc.setFillColor(15, 42, 95);
  doc.rect(0, 0, 595, 96, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("DashAI", 40, 42);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("ERP + AI Business Workspace", 40, 60);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("INVOICE", 430, 45);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(invoiceNumber, 430, 63);

  doc.setTextColor(15, 23, 42);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Bill To", 40, 135);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(client, 40, 153);
  doc.text("Indonesia", 40, 169);

  doc.setFont("helvetica", "bold");
  doc.text("Invoice Detail", 360, 135);

  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${row.date || new Date().toLocaleDateString("id-ID")}`, 360, 153);
  doc.text(`Due: ${row.due || row.dueDate || "-"}`, 360, 169);
  doc.text(`Status: ${row.status || "Pending"}`, 360, 185);

  autoTable(doc, {
    startY: 225,
    head: [["Description", "Qty", "Unit Price", "Tax", "Total"]],
    body: [
      [
        row.transaction ||
          row.description ||
          row.report ||
          "ERP Service / Business Invoice",
        "1",
        toRupiah(baseAmount),
        toRupiah(tax),
        toRupiah(grandTotal),
      ],
    ],
    styles: {
      fontSize: 10,
      cellPadding: 10,
    },
    headStyles: {
      fillColor: [15, 42, 95],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
  });

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } })
    .lastAutoTable.finalY;

  autoTable(doc, {
    startY: finalY + 24,
    margin: { left: 345 },
    body: [
      ["Subtotal", toRupiah(baseAmount)],
      ["PPN 11%", toRupiah(tax)],
      ["Grand Total", toRupiah(grandTotal)],
    ],
    styles: {
      fontSize: 10,
      cellPadding: 8,
    },
    columnStyles: {
      0: { fontStyle: "bold" },
      1: { halign: "right" },
    },
    didParseCell(data) {
      if (data.row.index === 2) {
        data.cell.styles.fillColor = [15, 42, 95];
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment Notes", 40, finalY + 110);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    "Mohon lakukan pembayaran sesuai total invoice. Invoice ini dibuat otomatis dari DashAI ERP.",
    40,
    finalY + 128,
    { maxWidth: 500 }
  );

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by DashAI ERP", 40, 790);

  doc.save(`${safeFileName(invoiceNumber)}.pdf`);
}

export function exportFinancialReportToPDF({
  title,
  columns,
  rows,
}: {
  title: string;
  columns: ModuleColumn[];
  rows: ModuleRow[];
}) {
  exportRowsToPDF({
    filename: `${title} Report`,
    title: `${title} Report`,
    description:
      "Laporan keuangan ini dibuat otomatis dari data DashAI ERP dan dapat digunakan sebagai bahan review internal.",
    columns,
    rows,
  });
}