export type FeatureKey = "product" | "hr" | "crm" | "finance" | "admin";

export type RelationConfig = {
  name: string;
  endpoint: string;
  foreignKey: string;
  displayField: string;
  displayKeys: string[];
  requiresCompanyId?: boolean;
};

export type ModuleResourceConfig = {
  featureKey: FeatureKey;
  moduleKey: string;
  endpoint: string;
  queryKey: string;
  sortBy?: string;

  createKeys: string[];
  updateKeys?: string[];

  uuidKeys?: string[];
  numericKeys?: string[];
  booleanKeys?: string[];

  aliases?: Record<string, string[]>;
  removeKeys?: string[];

  relations?: RelationConfig[];
};

const commonRelations: RelationConfig[] = [
  {
    name: "companies",
    endpoint: "/api/v1/companies",
    foreignKey: "company_id",
    displayField: "company_name",
    displayKeys: ["name", "legal_name", "company_name", "display_name"],
  },
  {
    name: "branches",
    endpoint: "/api/v1/companies/{company_id}/branches",
    foreignKey: "branch_id",
    displayField: "branch_name",
    displayKeys: [
      "name",
      "branch_name",
      "branch_code",
      "code",
      "display_name",
    ],
    requiresCompanyId: true,
  },
];

const productRelations: RelationConfig[] = [
  ...commonRelations,
  {
    name: "categories",
    endpoint: "/api/v1/products/categories",
    foreignKey: "category_id",
    displayField: "category_name",
    displayKeys: ["name", "category_name", "code"],
  },
  {
    name: "parentCategories",
    endpoint: "/api/v1/products/categories",
    foreignKey: "parent_category_id",
    displayField: "parent_category_name",
    displayKeys: ["name", "category_name", "code"],
  },
  {
    name: "products",
    endpoint: "/api/v1/products/items",
    foreignKey: "product_id",
    displayField: "product_name",
    displayKeys: ["name", "product_name", "sku"],
  },
  {
    name: "suppliers",
    endpoint: "/api/v1/products/suppliers",
    foreignKey: "supplier_id",
    displayField: "supplier_name",
    displayKeys: ["name", "supplier_name", "email", "phone"],
  },
];

const hrRelations: RelationConfig[] = [
  ...commonRelations,
  {
    name: "employees",
    endpoint: "/api/v1/hr/employees",
    foreignKey: "employee_id",
    displayField: "employee_name",
    displayKeys: ["full_name", "name", "employee_name", "employee_no", "email"],
  },
  {
    name: "leaveTypes",
    endpoint: "/api/v1/hr/leave-types",
    foreignKey: "leave_type_id",
    displayField: "leave_type_name",
    displayKeys: ["name", "code", "leave_type_name"],
  },
  {
    name: "reviewers",
    endpoint: "/api/v1/users",
    foreignKey: "reviewer_user_id",
    displayField: "reviewer_name",
    displayKeys: ["full_name", "name", "email"],
  },
  {
    name: "approvers",
    endpoint: "/api/v1/users",
    foreignKey: "approved_by_id",
    displayField: "approved_by_name",
    displayKeys: ["full_name", "name", "email"],
  },
];

const crmRelations: RelationConfig[] = [
  ...commonRelations,
  {
    name: "leads",
    endpoint: "/api/v1/crm/leads",
    foreignKey: "lead_id",
    displayField: "lead_name",
    displayKeys: ["name", "lead_name", "company_name", "email"],
  },
  {
    name: "contacts",
    endpoint: "/api/v1/crm/contacts",
    foreignKey: "contact_id",
    displayField: "contact_name",
    displayKeys: ["name", "contact_name", "company_name", "email", "phone"],
  },
  {
    name: "deals",
    endpoint: "/api/v1/crm/deals",
    foreignKey: "deal_id",
    displayField: "deal_name",
    displayKeys: ["title", "name", "deal_name"],
  },
  {
    name: "owners",
    endpoint: "/api/v1/users",
    foreignKey: "owner_user_id",
    displayField: "owner_name",
    displayKeys: ["full_name", "name", "email"],
  },
  {
    name: "assignees",
    endpoint: "/api/v1/users",
    foreignKey: "assigned_user_id",
    displayField: "assigned_user_name",
    displayKeys: ["full_name", "name", "email"],
  },
];

const financeRelations: RelationConfig[] = [
  ...commonRelations,
  {
    name: "cashAccounts",
    endpoint: "/api/v1/finance/cash-accounts",
    foreignKey: "cash_account_id",
    displayField: "cash_account_name",
    displayKeys: [
      "name",
      "cash_account_name",
      "account_name",
      "bank_name",
      "account_number",
    ],
  },
  {
    name: "periods",
    endpoint: "/api/v1/finance/accounting-periods",
    foreignKey: "period_id",
    displayField: "period_name",
    displayKeys: ["name", "period_name", "code"],
  },
  {
    name: "taxRates",
    endpoint: "/api/v1/finance/tax-rates",
    foreignKey: "tax_rate_id",
    displayField: "tax_rate_name",
    displayKeys: ["name", "tax_type", "rate_percent"],
  },
  {
    name: "transactions",
    endpoint: "/api/v1/finance/transactions",
    foreignKey: "transaction_id",
    displayField: "transaction_no_display",
    displayKeys: ["transaction_no", "reference_no", "description"],
  },
];

export const moduleRegistry: Record<
  FeatureKey,
  Record<string, ModuleResourceConfig>
> = {
  product: {
    overview: {
      featureKey: "product",
      moduleKey: "overview",
      endpoint: "/api/v1/products/items",
      queryKey: "items",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "branch_id",
        "category_id",
        "created_by_id",
        "sku",
        "barcode",
        "name",
        "description",
        "image_url",
        "product_type",
        "unit",
        "cost_price",
        "selling_price",
        "track_stock",
        "status",
      ],
      updateKeys: [
        "branch_id",
        "category_id",
        "sku",
        "barcode",
        "name",
        "description",
        "image_url",
        "product_type",
        "unit",
        "cost_price",
        "selling_price",
        "track_stock",
        "status",
      ],
      uuidKeys: ["company_id", "branch_id", "category_id", "created_by_id"],
      numericKeys: ["cost_price", "selling_price"],
      booleanKeys: ["track_stock"],
      aliases: {
        image_url: ["photo", "photo_url", "image", "attachment_url"],
        selling_price: ["price", "sale_price"],
      },
      removeKeys: [
        "photo",
        "photo_url",
        "image",
        "price",
        "category",
        "branch",
        "product",
      ],
      relations: productRelations,
    },

    categories: {
      featureKey: "product",
      moduleKey: "categories",
      endpoint: "/api/v1/products/categories",
      queryKey: "categories",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "parent_category_id",
        "code",
        "name",
        "description",
        "is_active",
      ],
      updateKeys: [
        "parent_category_id",
        "code",
        "name",
        "description",
        "is_active",
      ],
      uuidKeys: ["company_id", "parent_category_id"],
      booleanKeys: ["is_active"],
      relations: productRelations,
    },

    stock: {
      featureKey: "product",
      moduleKey: "stock",
      endpoint: "/api/v1/products/stocks",
      queryKey: "stock",
      sortBy: "updated_at",
      createKeys: [
        "company_id",
        "product_id",
        "branch_id",
        "quantity_on_hand",
        "reserved_quantity",
        "reorder_point",
      ],
      updateKeys: [
        "quantity_on_hand",
        "reserved_quantity",
        "reorder_point",
      ],
      uuidKeys: ["company_id", "product_id", "branch_id"],
      numericKeys: [
        "quantity_on_hand",
        "reserved_quantity",
        "reorder_point",
      ],
      aliases: {
        quantity_on_hand: ["stock", "quantity", "qty"],
        reserved_quantity: ["reserved"],
        reorder_point: ["reorder"],
      },
      removeKeys: [
        "stock",
        "quantity",
        "qty",
        "reserved",
        "reorder",
        "product",
        "branch",
      ],
      relations: productRelations,
    },

    suppliers: {
      featureKey: "product",
      moduleKey: "suppliers",
      endpoint: "/api/v1/products/suppliers",
      queryKey: "suppliers",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "name",
        "category",
        "contact_person",
        "email",
        "phone",
        "address",
        "lead_time_days",
        "status",
      ],
      updateKeys: [
        "name",
        "category",
        "contact_person",
        "email",
        "phone",
        "address",
        "lead_time_days",
        "status",
      ],
      uuidKeys: ["company_id"],
      numericKeys: ["lead_time_days"],
      relations: productRelations,
    },
  },

  hr: {
    employees: {
      featureKey: "hr",
      moduleKey: "employees",
      endpoint: "/api/v1/hr/employees",
      queryKey: "employees",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "branch_id",
        "user_id",
        "employee_no",
        "full_name",
        "email",
        "phone",
        "photo_url",
        "department_name",
        "job_title",
        "employment_type",
        "status",
        "hire_date",
        "resign_date",
        "base_salary",
      ],
      updateKeys: [
        "branch_id",
        "user_id",
        "employee_no",
        "full_name",
        "email",
        "phone",
        "photo_url",
        "department_name",
        "job_title",
        "employment_type",
        "status",
        "hire_date",
        "resign_date",
        "base_salary",
      ],
      uuidKeys: ["company_id", "branch_id", "user_id"],
      numericKeys: ["base_salary"],
      aliases: {
        photo_url: ["photo", "image_url", "attachment_url"],
      },
      removeKeys: ["photo", "image_url", "branch"],
      relations: hrRelations,
    },

    attendance: {
      featureKey: "hr",
      moduleKey: "attendance",
      endpoint: "/api/v1/hr/attendance",
      queryKey: "attendance",
      sortBy: "attendance_date",
      createKeys: [
        "company_id",
        "branch_id",
        "employee_id",
        "attendance_date",
        "check_in_at",
        "check_out_at",
        "status",
        "work_minutes",
        "overtime_minutes",
        "notes",
      ],
      updateKeys: [
        "check_in_at",
        "check_out_at",
        "status",
        "work_minutes",
        "overtime_minutes",
        "notes",
      ],
      uuidKeys: ["company_id", "branch_id", "employee_id"],
      numericKeys: ["work_minutes", "overtime_minutes"],
      aliases: {
        check_in_at: ["clock_in"],
        check_out_at: ["clock_out"],
      },
      removeKeys: ["clock_in", "clock_out", "employee", "branch"],
      relations: hrRelations,
    },

    "leave-types": {
      featureKey: "hr",
      moduleKey: "leave-types",
      endpoint: "/api/v1/hr/leave-types",
      queryKey: "leave-types",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "code",
        "name",
        "description",
        "default_days_per_year",
        "is_paid",
        "is_active",
      ],
      updateKeys: [
        "code",
        "name",
        "description",
        "default_days_per_year",
        "is_paid",
        "is_active",
      ],
      uuidKeys: ["company_id"],
      numericKeys: ["default_days_per_year"],
      booleanKeys: ["is_paid", "is_active"],
      aliases: {
        default_days_per_year: ["max_days"],
      },
      removeKeys: ["max_days"],
      relations: hrRelations,
    },

    "leave-requests": {
      featureKey: "hr",
      moduleKey: "leave-requests",
      endpoint: "/api/v1/hr/leave-requests",
      queryKey: "leave-requests",
      sortBy: "start_date",
      createKeys: [
        "company_id",
        "employee_id",
        "leave_type_id",
        "start_date",
        "end_date",
        "total_days",
        "reason",
        "status",
        "approved_by_id",
        "approved_at",
        "notes",
      ],
      updateKeys: [
        "leave_type_id",
        "start_date",
        "end_date",
        "total_days",
        "reason",
        "status",
        "approved_by_id",
        "approved_at",
        "notes",
      ],
      uuidKeys: [
        "company_id",
        "employee_id",
        "leave_type_id",
        "approved_by_id",
      ],
      numericKeys: ["total_days"],
      relations: hrRelations,
    },

    tasks: {
      featureKey: "hr",
      moduleKey: "tasks",
      endpoint: "/api/v1/hr/tasks",
      queryKey: "tasks",
      sortBy: "due_date",
      createKeys: [
        "company_id",
        "employee_id",
        "title",
        "description",
        "priority",
        "status",
        "due_date",
        "completion_score",
      ],
      updateKeys: [
        "employee_id",
        "title",
        "description",
        "priority",
        "status",
        "due_date",
        "completion_score",
      ],
      uuidKeys: ["company_id", "employee_id"],
      numericKeys: ["completion_score"],
      relations: hrRelations,
    },

    "payroll-runs": {
      featureKey: "hr",
      moduleKey: "payroll-runs",
      endpoint: "/api/v1/hr/payroll-runs",
      queryKey: "payroll-runs",
      sortBy: "period_start",
      createKeys: [
        "company_id",
        "period_start",
        "period_end",
        "status",
        "total_gross",
        "total_deduction",
        "total_net",
        "notes",
      ],
      updateKeys: [
        "period_start",
        "period_end",
        "status",
        "total_gross",
        "total_deduction",
        "total_net",
        "notes",
      ],
      uuidKeys: ["company_id"],
      numericKeys: ["total_gross", "total_deduction", "total_net"],
      relations: hrRelations,
    },

    "kpi-reviews": {
      featureKey: "hr",
      moduleKey: "kpi-reviews",
      endpoint: "/api/v1/hr/kpi-reviews",
      queryKey: "kpi-reviews",
      sortBy: "review_period",
      createKeys: [
        "company_id",
        "employee_id",
        "review_period",
        "target_value",
        "actual_value",
        "weight_score",
        "total_score",
        "status",
        "notes",
      ],
      updateKeys: [
        "employee_id",
        "review_period",
        "target_value",
        "actual_value",
        "weight_score",
        "total_score",
        "status",
        "notes",
      ],
      uuidKeys: ["company_id", "employee_id"],
      numericKeys: [
        "target_value",
        "actual_value",
        "weight_score",
        "total_score",
      ],
      aliases: {
        total_score: ["score"],
      },
      relations: hrRelations,
    },
  },

  crm: {
    leads: {
      featureKey: "crm",
      moduleKey: "leads",
      endpoint: "/api/v1/crm/leads",
      queryKey: "leads",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "branch_id",
        "owner_user_id",
        "name",
        "company_name",
        "email",
        "phone",
        "source",
        "status",
        "score",
        "notes",
      ],
      updateKeys: [
        "branch_id",
        "owner_user_id",
        "name",
        "company_name",
        "email",
        "phone",
        "source",
        "status",
        "score",
        "notes",
      ],
      uuidKeys: ["company_id", "branch_id", "owner_user_id"],
      numericKeys: ["score"],
      relations: crmRelations,
    },

    contacts: {
      featureKey: "crm",
      moduleKey: "contacts",
      endpoint: "/api/v1/crm/contacts",
      queryKey: "contacts",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "branch_id",
        "lead_id",
        "name",
        "company_name",
        "email",
        "phone",
        "position",
        "status",
        "notes",
      ],
      updateKeys: [
        "branch_id",
        "lead_id",
        "name",
        "company_name",
        "email",
        "phone",
        "position",
        "status",
        "notes",
      ],
      uuidKeys: ["company_id", "branch_id", "lead_id"],
      relations: crmRelations,
    },

    deals: {
      featureKey: "crm",
      moduleKey: "deals",
      endpoint: "/api/v1/crm/deals",
      queryKey: "deals",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "branch_id",
        "lead_id",
        "contact_id",
        "owner_user_id",
        "title",
        "stage",
        "estimated_value",
        "probability_percent",
        "expected_close_date",
        "status",
        "notes",
      ],
      updateKeys: [
        "branch_id",
        "lead_id",
        "contact_id",
        "owner_user_id",
        "title",
        "stage",
        "estimated_value",
        "probability_percent",
        "expected_close_date",
        "status",
        "notes",
      ],
      uuidKeys: [
        "company_id",
        "branch_id",
        "lead_id",
        "contact_id",
        "owner_user_id",
      ],
      numericKeys: ["estimated_value", "probability_percent"],
      relations: crmRelations,
    },

    activities: {
      featureKey: "crm",
      moduleKey: "activities",
      endpoint: "/api/v1/crm/activities",
      queryKey: "activities",
      sortBy: "due_at",
      createKeys: [
        "company_id",
        "branch_id",
        "lead_id",
        "contact_id",
        "deal_id",
        "assigned_user_id",
        "activity_type",
        "subject",
        "description",
        "due_at",
        "status",
        "result",
      ],
      updateKeys: [
        "branch_id",
        "lead_id",
        "contact_id",
        "deal_id",
        "assigned_user_id",
        "activity_type",
        "subject",
        "description",
        "due_at",
        "status",
        "result",
      ],
      uuidKeys: [
        "company_id",
        "branch_id",
        "lead_id",
        "contact_id",
        "deal_id",
        "assigned_user_id",
      ],
      aliases: {
        due_at: ["activity_date", "scheduled_at"],
      },
      removeKeys: ["activity_date", "scheduled_at"],
      relations: crmRelations,
    },

    campaigns: {
      featureKey: "crm",
      moduleKey: "campaigns",
      endpoint: "/api/v1/crm/campaigns",
      queryKey: "campaigns",
      sortBy: "start_date",
      createKeys: [
        "company_id",
        "branch_id",
        "name",
        "channel",
        "budget_amount",
        "leads_count",
        "start_date",
        "end_date",
        "status",
        "notes",
      ],
      updateKeys: [
        "branch_id",
        "name",
        "channel",
        "budget_amount",
        "leads_count",
        "start_date",
        "end_date",
        "status",
        "notes",
      ],
      uuidKeys: ["company_id", "branch_id"],
      numericKeys: ["budget_amount", "leads_count"],
      aliases: {
        budget_amount: ["budget", "amount"],
      },
      removeKeys: ["budget", "amount"],
      relations: crmRelations,
    },
  },

  finance: {
    overview: {
      featureKey: "finance",
      moduleKey: "overview",
      endpoint: "/api/v1/finance/transactions",
      queryKey: "transactions",
      sortBy: "transaction_date",
      createKeys: [],
      relations: financeRelations,
    },

    transactions: {
      featureKey: "finance",
      moduleKey: "transactions",
      endpoint: "/api/v1/finance/transactions",
      queryKey: "transactions",
      sortBy: "transaction_date",
      createKeys: [
        "company_id",
        "period_id",
        "cash_account_id",
        "transaction_no",
        "transaction_date",
        "transaction_type",
        "cashflow_activity",
        "status",
        "counterparty_name",
        "reference_no",
        "proof_url",
        "attachment_url",
        "source_module",
        "source_id",
        "subtotal_amount",
        "discount_amount",
        "tax_amount",
        "total_amount",
        "description",
        "posted_at",
        "created_by",
      ],
      updateKeys: [
        "period_id",
        "cash_account_id",
        "transaction_no",
        "transaction_date",
        "transaction_type",
        "cashflow_activity",
        "status",
        "counterparty_name",
        "reference_no",
        "proof_url",
        "attachment_url",
        "source_module",
        "source_id",
        "subtotal_amount",
        "discount_amount",
        "tax_amount",
        "total_amount",
        "description",
        "posted_at",
        "created_by",
      ],
      uuidKeys: [
        "company_id",
        "period_id",
        "cash_account_id",
        "source_id",
        "created_by",
      ],
      numericKeys: [
        "subtotal_amount",
        "discount_amount",
        "tax_amount",
        "total_amount",
      ],
      aliases: {
        transaction_date: ["date"],
        total_amount: ["amount", "total"],
        transaction_type: ["type"],
      },
      removeKeys: [
        "date",
        "amount",
        "total",
        "type",
        "account_name",
        "cash_account_name",
      ],
      relations: financeRelations,
    },

    invoices: {
      featureKey: "finance",
      moduleKey: "invoices",
      endpoint: "/api/v1/finance/invoices",
      queryKey: "invoices",
      sortBy: "invoice_date",
      createKeys: [
        "company_id",
        "branch_id",
        "invoice_no",
        "client_name",
        "invoice_date",
        "due_date",
        "subtotal_amount",
        "tax_amount",
        "total_amount",
        "paid_amount",
        "status",
        "source_module",
        "source_id",
        "notes",
      ],
      updateKeys: [
        "branch_id",
        "invoice_no",
        "client_name",
        "invoice_date",
        "due_date",
        "subtotal_amount",
        "tax_amount",
        "total_amount",
        "paid_amount",
        "status",
        "source_module",
        "source_id",
        "notes",
      ],
      uuidKeys: ["company_id", "branch_id", "source_id"],
      numericKeys: [
        "subtotal_amount",
        "tax_amount",
        "total_amount",
        "paid_amount",
      ],
      aliases: {
        client_name: ["customer_name", "customer", "client"],
        invoice_date: ["issue_date", "date"],
        total_amount: ["amount", "total"],
      },
      removeKeys: [
        "customer_name",
        "customer",
        "client",
        "issue_date",
        "date",
        "amount",
        "total",
        "discount_amount",
        "attachment_url",
        "proof_url",
      ],
      relations: financeRelations,
    },

    cashflow: {
      featureKey: "finance",
      moduleKey: "cashflow",
      endpoint: "/api/v1/finance/cashflow-snapshots",
      queryKey: "cashflow",
      sortBy: "report_date",
      createKeys: [
        "company_id",
        "period_id",
        "report_date",
        "beginning_cash_balance",
        "operating_cash_in",
        "operating_cash_out",
        "investing_cash_in",
        "investing_cash_out",
        "financing_cash_in",
        "financing_cash_out",
        "net_cashflow",
        "ending_cash_balance",
      ],
      updateKeys: [
        "period_id",
        "report_date",
        "beginning_cash_balance",
        "operating_cash_in",
        "operating_cash_out",
        "investing_cash_in",
        "investing_cash_out",
        "financing_cash_in",
        "financing_cash_out",
        "net_cashflow",
        "ending_cash_balance",
      ],
      uuidKeys: ["company_id", "period_id"],
      numericKeys: [
        "beginning_cash_balance",
        "operating_cash_in",
        "operating_cash_out",
        "investing_cash_in",
        "investing_cash_out",
        "financing_cash_in",
        "financing_cash_out",
        "net_cashflow",
        "ending_cash_balance",
      ],
      aliases: {
        report_date: ["snapshot_date", "date"],
        beginning_cash_balance: ["opening_balance", "beginning"],
        ending_cash_balance: ["closing_balance", "ending"],
      },
      removeKeys: [
        "snapshot_date",
        "date",
        "opening_balance",
        "closing_balance",
        "beginning",
        "ending",
      ],
      relations: financeRelations,
    },

    taxes: {
      featureKey: "finance",
      moduleKey: "taxes",
      endpoint: "/api/v1/finance/tax-records",
      queryKey: "taxes",
      sortBy: "created_at",
      createKeys: [
        "company_id",
        "period_id",
        "tax_rate_id",
        "transaction_id",
        "tax_type",
        "tax_period",
        "taxable_amount",
        "tax_amount",
        "paid_amount",
        "status",
        "due_date",
        "paid_date",
        "reported_date",
        "reference_no",
        "notes",
      ],
      updateKeys: [
        "period_id",
        "tax_rate_id",
        "transaction_id",
        "tax_type",
        "tax_period",
        "taxable_amount",
        "tax_amount",
        "paid_amount",
        "status",
        "due_date",
        "paid_date",
        "reported_date",
        "reference_no",
        "notes",
      ],
      uuidKeys: ["company_id", "period_id", "tax_rate_id", "transaction_id"],
      numericKeys: ["taxable_amount", "tax_amount", "paid_amount"],
      aliases: {
        tax_period: ["period", "month"],
        paid_date: ["payment_date"],
        tax_amount: ["amount"],
      },
      removeKeys: [
        "period",
        "month",
        "payment_date",
        "amount",
        "attachment_url",
        "proof_url",
      ],
      relations: financeRelations,
    },

    ledger: {
      featureKey: "finance",
      moduleKey: "ledger",
      endpoint: "/api/v1/finance/journal-entries",
      queryKey: "ledger",
      sortBy: "journal_date",
      createKeys: [
        "company_id",
        "period_id",
        "transaction_id",
        "journal_no",
        "journal_date",
        "status",
        "memo",
        "total_debit",
        "total_credit",
        "is_balanced",
        "posted_at",
        "created_by",
      ],
      updateKeys: [
        "period_id",
        "transaction_id",
        "journal_no",
        "journal_date",
        "status",
        "memo",
        "total_debit",
        "total_credit",
        "is_balanced",
        "posted_at",
        "created_by",
      ],
      uuidKeys: ["company_id", "period_id", "transaction_id", "created_by"],
      numericKeys: ["total_debit", "total_credit"],
      booleanKeys: ["is_balanced"],
      aliases: {
        journal_date: ["entry_date", "date"],
        total_debit: ["debit_amount", "debit"],
        total_credit: ["credit_amount", "credit"],
      },
      removeKeys: [
        "entry_date",
        "date",
        "debit_amount",
        "debit",
        "credit_amount",
        "credit",
      ],
      relations: financeRelations,
    },
  },

  admin: {
    companies: {
      featureKey: "admin",
      moduleKey: "companies",
      endpoint: "/api/v1/companies",
      queryKey: "companies",
      sortBy: "created_at",
      createKeys: ["name"],
    },

    users: {
      featureKey: "admin",
      moduleKey: "users",
      endpoint: "/api/v1/users",
      queryKey: "users",
      sortBy: "created_at",
      createKeys: [],
    },

    settings: {
      featureKey: "admin",
      moduleKey: "settings",
      endpoint: "/api/v1/admin/settings",
      queryKey: "settings",
      sortBy: "created_at",
      createKeys: [],
    },
  },
};

export function normalizeModuleKey(featureKey: FeatureKey, moduleKey?: string) {
  const raw = String(moduleKey || "overview").trim().toLowerCase();

  const aliases: Record<FeatureKey, Record<string, string>> = {
    product: {
      overview: "overview",
      products: "overview",
      product: "overview",
      items: "overview",
      item: "overview",
      categories: "categories",
      category: "categories",
      stock: "stock",
      stocks: "stock",
      suppliers: "suppliers",
      supplier: "suppliers",
    },

    hr: {
      overview: "employees",
      employees: "employees",
      employee: "employees",
      attendance: "attendance",
      leave: "leave-requests",
      leaves: "leave-requests",
      "leave-types": "leave-types",
      leave_types: "leave-types",
      leavetypes: "leave-types",
      "leave-requests": "leave-requests",
      leave_requests: "leave-requests",
      leaverequests: "leave-requests",
      tasks: "tasks",
      task: "tasks",
      payroll: "payroll-runs",
      "payroll-runs": "payroll-runs",
      payroll_runs: "payroll-runs",
      kpi: "kpi-reviews",
      kpis: "kpi-reviews",
      "kpi-reviews": "kpi-reviews",
      kpi_reviews: "kpi-reviews",
    },

    crm: {
      overview: "leads",
      leads: "leads",
      lead: "leads",
      contacts: "contacts",
      contact: "contacts",
      customers: "contacts",
      customer: "contacts",
      deals: "deals",
      deal: "deals",
      pipeline: "deals",
      pipelines: "deals",
      activities: "activities",
      activity: "activities",
      campaigns: "campaigns",
      campaign: "campaigns",
    },

    finance: {
      overview: "overview",
      transactions: "transactions",
      transaction: "transactions",
      invoices: "invoices",
      invoice: "invoices",
      cashflow: "cashflow",
      "cashflow-snapshots": "cashflow",
      taxes: "taxes",
      tax: "taxes",
      "tax-records": "taxes",
      ledger: "ledger",
      "journal-entries": "ledger",
    },

    admin: {
      companies: "companies",
      users: "users",
      settings: "settings",
    },
  };

  return aliases[featureKey]?.[raw] ?? raw;
}

export function getModuleResource(featureKey: FeatureKey, moduleKey?: string) {
  const normalizedKey = normalizeModuleKey(featureKey, moduleKey);
  const resource = moduleRegistry[featureKey]?.[normalizedKey];

  if (!resource) {
    throw new Error(`Module resource belum dibuat untuk ${featureKey}/${moduleKey}`);
  }

  return resource;
}